### ISSUE TITLE
Inconsistent version numbers

### ISSUE THREAD

**Issue by Rhialto** [SDL-Hercules-390/telnet#7]
And here, too, `README.md` and `build` disagree.

Can you tell I'm trying to clean up packaging for pkgsrc, and trying to assign the correct versions to everything? :)

**Comment by Fish-Git** [comment]
The version number of the _package_ is defined by statements within the package's [CMake script](https://github.com/SDL-Hercules-390/telnet/blob/master/CMakeLists.txt):

https://github.com/SDL-Hercules-390/telnet/blob/2aca101e06ca84526c1a63c0f65e05fe11522c3b/CMakeLists.txt#L9-L18

which matches both the packages's documentation (README) and what is reported by Hercules too during startup as well:

<pre>
HHC01417I Built with crypto external package version 1.0.0.49-g837705e
HHC01417I Built with decNumber external package version 3.68.0.99-gda66509
HHC01417I Built with SoftFloat external package version 3.5.0.102-g42f2f99
<b>HHC01417I Built with telnet external package version 1.0.0.59-g2aca101</b>
</pre>

Closing as Invalid (User Error).

**Comment by Rhialto** [comment]
Thanks!
