### ISSUE TITLE
MacOS building ?

### ISSUE THREAD

**Issue by n9yty** [SDL-Hercules-390/telnet#8]
The included external libraries seem to be Windows and Linux only, macOS can't link to them, invalid byte format.

I tried to follow the build instructions:

make top-level directory:
$ mkdir hercext
$ cd hercext

Pull in the various external repos, like this one for example:
$ git clone "https://github.com/SDL-Hercules-390/telnet.git" telnet-repo

Make output build directory
$ mkdir hercpkgs

I thought I followed the notes...
$ mkdir telnet
$ cd telnet
$ ../telnet-repo/build --pkgname . --arch 64 --install ../hercpkgs

But I get this:
```
cmdline = build --pkgname telnet --arch 64 --install ../hercpkgs

Build of 64-bit Release version of telnet begun on Thu 03/23/23 at 12:57:35

Configuring telnet64.Release ...

CMake Error: The source directory "/Users/n9yty/Projects/hercules/hercext/telnet/telnet-repo" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

ERROR: cmake has failed! rc=1

Build FAILED on Thu 03/23/23 at 12:57:35
```

I'm not sure why it wants to keep pulling in the current work directory into the source directory...  I tried to specify --pkgdir without any help:

$ ../telnet-repo/build --pkgdir ../telnet-repo --pkgname telnet --arch 64 --install ../hercpkgs

output:
```
cmdline = build --pkgdir ../telnet-repo --pkgname telnet --arch 64 --install ../hercpkgs

Build of 64-bit Release version of telnet begun on Thu 03/23/23 at 12:58:08

Configuring telnet64.Release ...

CMake Error: The source directory "/Users/n9yty/Projects/hercules/hercext/telnet/telnet-repo" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

ERROR: cmake has failed! rc=1

Build FAILED on Thu 03/23/23 at 12:58:08
```

Are there any updated docs for building on macOS? Or is it not really supported any longer?

**Comment by wrljet** [comment]
Steve,

On macOS I recommend you give my [Hercules-Helper](https://github.com/wrljet/hercules-helper#readme) a try.
It will handle the SDL-Hercules build process for you, and works on macOS, x86 and Apple silicon.

Be sure to read the README fully before starting.  And if you have any trouble or questions please do not hesitate to ask.

Bill

**Comment by n9yty** [comment]
I will have a look!  I just tried to hardcode the full path into the --pkgdir and it also built it properly, although I haven't tested it yet.

**Comment by wrljet** [comment]
For what it's worth, Hercules-Helper doesn't use Fish's outer level `build` scripts for the external packages.
I do those with CMake directly.

There's other landmines lurking beyond the external packages on Mac as well.

**Comment by n9yty** [comment]
@wrljet I give you huge thanks, that sure did simplify things! I have binaries now. :)

I'm glad I don't have to know about other landmines lurking. I've been building on MacOSX since the first beta was out, trying to bring things over, and always there are plenty of problems to deal with. :) It has gotten better and worse over the years. LoL

This is a whole area  of "retro" I never even knew about until I stumbled across the moshix YouTube channel, and now I have to get neck deep in it. :)

**Comment by wrljet** [comment]
> @wrljet I give you huge thanks, that sure did simplify things! I have binaries now. :)

That was quick!

Moshix runs a Discord chat group catering to mainframes, MVS and VM, Hercules, and retro topics in general.
If you're interested in that, there's a link to it in the description blurb of his recent video "Freshly Genned MVS/CommunityEdition - M233".

Bill
